import XCTest
import Foundation
@testable import ReplicatorApply
@testable import ReplicatorCodec
@testable import ReplicatorCapture

final class DDLTests: XCTestCase {
    func parse(_ sql: String,database: String?="poc") throws -> DDLStatement {
        try DDLStatement.parse(QueryControl(database:database,sql:Data(sql.utf8),errorCode:0,statusVariables:Data()))
    }
    func testCreateMapsExplicitEncodingAndPreservesColumnOrderAndNonLeadingKey() throws {
        let result=try parse("CREATE TABLE `poc`.`new``name` (payload VARCHAR(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL, k BIGINT UNSIGNED, PRIMARY KEY(k)) ENGINE=InnoDB;")
        guard case .create(let table)=result else {return XCTFail("not CREATE")}
        XCTAssertEqual(table.table,"new`name")
        XCTAssertEqual(table.columns.map(\.name),["payload","k"])
        XCTAssertEqual(table.columns[0].collation,"utf8mb4_unicode_ci")
        XCTAssertFalse(table.columns[1].nullable)
        XCTAssertEqual(table.primaryKey,"k")
    }
    func testAcceptedAlterRenameAndGeneratedDropSyntax() throws {
        let t=TableName(database:"poc",table:"t")
        XCTAssertEqual(try parse("ALTER TABLE t ADD COLUMN n INT UNSIGNED NULL DEFAULT NULL AFTER k"),.add(t,ApplyColumn(name:"n",type:"int unsigned",nullable:true,collation:nil),.after("k")))
        XCTAssertEqual(try parse("ALTER TABLE t ADD b VARBINARY(12) FIRST"),.add(t,ApplyColumn(name:"b",type:"varbinary(12)",nullable:true,collation:nil),.first))
        XCTAssertEqual(try parse("ALTER TABLE t DROP COLUMN b"),.dropColumn(t,"b"))
        XCTAssertEqual(try parse("RENAME TABLE t TO other"),.rename(t,TableName(database:"poc",table:"other")))
        XCTAssertEqual(try parse("DROP TABLE `poc`.`t` /* generated by server */",database:nil),.drop(t))
    }
    func testUnsupportedDDLNeverFallsThroughToRawSQL() throws {
        for sql in [
            "CREATE TEMPORARY TABLE t(k INT PRIMARY KEY) ENGINE=InnoDB",
            "CREATE TABLE t(k INT PRIMARY KEY) ENGINE=MyISAM",
            "CREATE TABLE t(k INT PRIMARY KEY) ENGINE=InnoDB AS SELECT 1",
            "CREATE TABLE t(k INT PRIMARY KEY AUTO_INCREMENT) ENGINE=InnoDB",
            "CREATE TABLE t(k INT PRIMARY KEY,v VARCHAR(10)) ENGINE=InnoDB",
            "CREATE TABLE t(k INT PRIMARY KEY,v JSON) ENGINE=InnoDB",
            "CREATE TABLE t(k INT PRIMARY KEY,INDEX(k)) ENGINE=InnoDB",
            "ALTER TABLE t ADD n INT NOT NULL", "ALTER TABLE t ADD n INT DEFAULT 7",
            "ALTER TABLE t ADD n INT, ADD m INT", "ALTER TABLE t MODIFY k BIGINT",
            "ALTER TABLE t ADD n INT PRIMARY KEY", "ALTER TABLE t ADD n INT /*!80000 INVISIBLE */",
            "DROP TABLE IF EXISTS t", "DROP TABLE t,other", "DROP TABLE t; DROP DATABASE poc",
            "RENAME TABLE t TO otherdb.t", "TRUNCATE TABLE t", "CREATE DATABASE d",
            "ALTER TABLE t ADD n VARCHAR(10) CHARACTER SET latin1 COLLATE latin1_bin",
            "ALTER TABLE t ADD n INT DEFAULT (1+1)", "DROP TABLE \"t\"", "DROP TABLE t -- comment"
        ] {XCTAssertThrowsError(try parse(sql),sql)}
        XCTAssertThrowsError(try parse("DROP TABLE t",database:nil))
    }
    func testTargetUUIDIsNotAConfigurationInput() throws {
        let fields: [String:Any]=["host":"target","port":3306,"username":"u","passwordEnvironment":"P","serverHostname":"target","nativeAutoStartDisabled":true]
        XCTAssertNoThrow(try JSONDecoder().decode(TargetConfiguration.self,from:JSONSerialization.data(withJSONObject:fields)))
        var legacy=fields;legacy["targetUUID"]="REPLACE_TARGET_UUID"
        XCTAssertThrowsError(try JSONDecoder().decode(TargetConfiguration.self,from:JSONSerialization.data(withJSONObject:legacy))) {error in
            XCTAssertTrue(String(describing:error).contains("remove targetUUID"))
        }
    }
    func ddlGroup(_ base: CompleteTransaction,sql: String) -> CompleteTransaction {
        let old=base.events.last!
        let event=DecodedEvent(offset:old.offset,eventSize:old.eventSize,control:.query(QueryControl(database:"poc",sql:Data(sql.utf8),errorCode:0,statusVariables:Data())),rowFlags:nil,eventType:2,eventName:"Query",timestamp:old.timestamp,serverID:old.serverID,nextPosition:old.nextPosition,flags:0,sha256:old.sha256,tableID:nil,database:"poc",table:nil,number:nil,detailBase64:nil,detailText:sql,rows:[],rawBase64:old.rawBase64)
        return CompleteTransaction(start:base.start,end:base.end,gtid:base.gtid,anonymous:false,outcome:.statement,events:[base.events[0],event])
    }
    func testDDLJournalVersionsSchemaAndPrunesOnlyUnreferencedCompletedHistory() throws {
        #if os(Linux)
        let helpers=ApplyTests(name:"fixtures",testClosure:{_ in})
        #else
        let helpers=ApplyTests()
        #endif
        let parent=FileManager.default.temporaryDirectory.appendingPathComponent(UUID().uuidString)
        try FileManager.default.createDirectory(at:parent,withIntermediateDirectories:true)
        defer {try? FileManager.default.removeItem(at:parent)}
        let c=try helpers.config(parent.appendingPathComponent("state").path,storage:["historyRetentionSeconds":60])
        var now=Date(timeIntervalSince1970:1_700_000_000),free=Int64.max/4
        let store=try StateStore(configuration:c,now:{now},freeDisk:{_ in free})
        let db=store.directory.appendingPathComponent("state.sqlite"),groups=try helpers.groups(),table=helpers.tables()[0]
        try store.bindTargetIdentity("00000000-0000-0000-0000-000000000001")
        let create=ddlGroup(groups[0],sql:"CREATE TABLE items(id INT PRIMARY KEY) ENGINE=InnoDB")
        let plan=PreparedDDL(statement:.create(table),before:nil,after:table,sql:"CREATE TABLE poc.items (...) ENGINE=MyISAM")
        try store.begin(create)
        XCTAssertThrowsError(try store.complete(create,rowCount:0,ddl:plan))
        try store.ddlIntent(plan,event:create.events[1],coordinate:create.start)
        XCTAssertEqual(try helpers.sqlite(db,"SELECT status FROM ddl_intents"),[["PENDING"]])
        XCTAssertEqual(try helpers.sqlite(db,"SELECT COUNT(*) FROM schemas"),[["0"]])
        try store.complete(create,rowCount:0,ddl:plan)
        let mutation=try DMLPlan.make(groups[1],tables:[table])[0]
        try store.begin(groups[1]);try store.intent(0,mutation);try store.rowDone(0);try store.complete(groups[1],rowCount:1)
        let after=ApplyTable(database:table.database,table:table.table,columns:table.columns.filter{$0.name != "value"},primaryKey:"id")
        let alter=ddlGroup(groups[2],sql:"ALTER TABLE items DROP COLUMN value")
        let change=PreparedDDL(statement:.dropColumn(TableName(database:"poc",table:"items"),"value"),before:table,after:after,sql:"ALTER TABLE `poc`.`items` DROP COLUMN `value`")
        try store.begin(alter);try store.ddlIntent(change,event:alter.events[1],coordinate:alter.start);try store.complete(alter,rowCount:0,ddl:change)
        XCTAssertEqual(try helpers.sqlite(db,"SELECT current FROM schemas ORDER BY id"),[["0"],["1"]])
        XCTAssertEqual(try helpers.sqlite(db,"SELECT transactions_applied,rows_applied,ddl_applied FROM state"),[["3","1","2"]])
        let drop=ddlGroup(groups[3],sql:"DROP TABLE items")
        let removal=PreparedDDL(statement:.drop(TableName(database:"poc",table:"items")),before:after,after:nil,sql:"DROP TABLE `poc`.`items`")
        try store.begin(drop);try store.ddlIntent(removal,event:drop.events[1],coordinate:drop.start)
        now.addTimeInterval(120);free=c.policy.minimumFreeDiskBytes+c.policy.maximumSQLiteBytes*3/2
        try store.ensureCapacity()
        XCTAssertEqual(try helpers.sqlite(db,"SELECT status FROM ddl_intents"),[["PENDING"]])
        XCTAssertEqual(try helpers.sqlite(db,"SELECT current FROM schemas"),[["1"]])
        XCTAssertEqual(try store.durableAppliedGTIDs(),helpers.sid+":1-13")
        XCTAssertEqual(try helpers.sqlite(db,"SELECT COUNT(*) FROM row_intents"),[["0"]])
    }
}
