import XCTest
import Foundation
@testable import ReplicatorApply
@testable import ReplicatorCodec
@testable import ReplicatorCapture

final class DDLTests: XCTestCase {
    func parse(_ sql: String,database: String?="poc") throws -> DDLStatement {
        try DDLStatement.parse(QueryControl(database:database,sql:Data(sql.utf8),errorCode:0,statusVariables:Data()))
    }
    func testCreatePreservesExplicitEncodingAndColumnOrderWithoutEngineRewrite() throws {
        let result=try parse("CREATE TABLE `poc`.`new``name` (payload VARCHAR(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL, k BIGINT UNSIGNED, PRIMARY KEY(k));")
        guard case .create(let table,_)=result else {return XCTFail("not CREATE")}
        XCTAssertEqual(table.table,"new`name")
        XCTAssertEqual(table.columns.map(\.name),["payload","k"])
        XCTAssertEqual(table.columns[0].collation,"utf8mb4_0900_ai_ci")
        XCTAssertEqual(table.columns[0].characterSet,"utf8mb4")
        XCTAssertFalse(table.columns[1].nullable)
        XCTAssertEqual(table.primaryKey,"k")
    }
    func testAcceptedAlterRenameAndGeneratedDropSyntax() throws {
        let t=TableName(database:"poc",table:"t")
        XCTAssertEqual(try parse("ALTER TABLE t ADD COLUMN n INT UNSIGNED NULL DEFAULT NULL AFTER k"),.add(t,ApplyColumn(name:"n",type:"int unsigned",nullable:true,collation:nil),.after("k")))
        XCTAssertEqual(try parse("ALTER TABLE t ADD b VARBINARY(12) FIRST"),.add(t,ApplyColumn(name:"b",type:"varbinary(12)",nullable:true,collation:nil),.first))
        XCTAssertEqual(try parse("ALTER TABLE t DROP COLUMN b"),.dropColumn(t,"b"))
        XCTAssertEqual(try parse("RENAME TABLE t TO other"),.rename(t,TableName(database:"poc",table:"other")))
        XCTAssertEqual(try parse("DROP TABLE `poc`.`t` /* generated by server */",database:nil),.drop(t))
    }
    func testConditionalAndLikeStatementsRetainNamesAndConditions() throws {
        let t=TableName(database:"poc",table:"t"),template=TableName(database:"otherdb",table:"template")
        XCTAssertEqual(try parse("DROP TABLE IF EXISTS t /* generated by server */"),.dropIfPresent(t))
        XCTAssertEqual(try parse("CREATE TABLE t LIKE otherdb.template"),.createLike(t,template,ifNotExists:false))
        XCTAssertEqual(try parse("CREATE TABLE IF NOT EXISTS t LIKE otherdb.template"),.createLike(t,template,ifNotExists:true))
        guard case .createIfAbsent(let table,let engine)=try parse("CREATE TABLE IF NOT EXISTS t(id INT PRIMARY KEY) ENGINE='DEFAULT'") else {return XCTFail("missing condition")}
        XCTAssertEqual(table.table,"t");XCTAssertEqual(engine,.defaultEngine)
        XCTAssertThrowsError(try parse("CREATE TABLE t LIKE template",database:nil))
    }
    func testUnsupportedDDLNeverFallsThroughToRawSQL() throws {
        for sql in [
            "CREATE TEMPORARY TABLE t(k INT PRIMARY KEY) ENGINE=InnoDB",
            "CREATE TABLE t(k INT PRIMARY KEY) ENGINE=InnoDB",
            "CREATE TABLE t(k INT PRIMARY KEY) ENGINE=DEFAULT",
            "CREATE TABLE t(k INT PRIMARY KEY) ENGINE=InnoDB AS SELECT 1",
            "CREATE TABLE t(k INT PRIMARY KEY AUTO_INCREMENT) ENGINE=InnoDB",
            "CREATE TABLE t(k INT PRIMARY KEY,v VARCHAR(10)) ENGINE=InnoDB",
            "CREATE TABLE t(k INT PRIMARY KEY,v JSON) ENGINE=InnoDB",
            "CREATE TABLE t(k INT PRIMARY KEY,INDEX(k)) ENGINE=InnoDB",
            "ALTER TABLE t ADD n INT NOT NULL", "ALTER TABLE t ADD n INT DEFAULT 7",
            "ALTER TABLE t ADD n INT, ADD m INT", "ALTER TABLE t MODIFY k BIGINT",
            "ALTER TABLE t ADD n INT PRIMARY KEY", "ALTER TABLE t ADD n INT /*!80000 INVISIBLE */",
            "DROP TABLE IF NOT EXISTS t", "CREATE TABLE IF EXISTS t(id INT PRIMARY KEY)", "CREATE TABLE t LIKE x; DROP TABLE x", "CREATE TABLE t LIKE x ENGINE=MyISAM", "DROP TABLE t,other", "DROP TABLE t; DROP DATABASE poc",
            "RENAME TABLE t TO otherdb.t", "CREATE DATABASE d",
            "ALTER TABLE t ADD n INT DEFAULT (1+1)", "DROP TABLE \"t\"", "DROP TABLE t -- comment"
        ] {XCTAssertThrowsError(try parse(sql),sql)}
        XCTAssertThrowsError(try parse("DROP TABLE t",database:nil))
    }
    func testOmittedDefaultsCollateOnlyAndQuotedEngineRemainUnresolvedUntilTargetDiscovery() throws {
        for engine in [""," ENGINE=MyISAM"," ENGINE='DEFAULT'"] {
            guard case .create(let table,_)=try parse("CREATE TABLE t(id INT PRIMARY KEY,v VARCHAR(10),b VARCHAR(5) COLLATE utf8mb4_bin)"+engine) else {return XCTFail("not CREATE")}
            XCTAssertNil(table.columns[1].collation);XCTAssertNil(table.columns[1].characterSet)
            XCTAssertEqual(table.columns[2].collation,"utf8mb4_bin");XCTAssertNil(table.columns[2].characterSet)
        }
        XCTAssertEqual(try parse("TRUNCATE TABLE t"),.truncate(TableName(database:"poc",table:"t")))
        guard case .create(let table,_)=try parse("CREATE TABLE t(id INT PRIMARY KEY) DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci") else {return XCTFail("not CREATE")}
        XCTAssertEqual(table.defaultCharacterSet,"utf8mb4");XCTAssertEqual(table.defaultCollation,"utf8mb4_unicode_ci")
    }
    func testTypedQueryContextRequiresCompleteCharsetAndSQLModeMetadata() throws {
        let status=Data([1,0,0,0,0,0,0,0,0,4,45,0,224,0,255,0,18,45,0])
        let query=QueryControl(database:"poc",sql:Data(),errorCode:0,statusVariables:status)
        let context=try QuerySessionContext(query:query)
        XCTAssertEqual(context.clientCharset,45);XCTAssertEqual(context.defaultUTF8MB4Collation,45)
        for bytes in [Data(),Data(status.dropLast()),status+Data([255])] {
            XCTAssertThrowsError(try QuerySessionContext(query:QueryControl(database:"poc",sql:Data(),errorCode:0,statusVariables:bytes)))
        }
    }
    func testTargetUUIDIsNotAConfigurationInput() throws {
        let fields: [String:Any]=["host":"target","port":3306,"username":"u","passwordEnvironment":"P","serverHostname":"target","nativeAutoStartDisabled":true]
        XCTAssertNoThrow(try JSONDecoder().decode(TargetConfiguration.self,from:JSONSerialization.data(withJSONObject:fields)))
        var legacy=fields;legacy["targetUUID"]="REPLACE_TARGET_UUID"
        XCTAssertThrowsError(try JSONDecoder().decode(TargetConfiguration.self,from:JSONSerialization.data(withJSONObject:legacy))) {error in
            XCTAssertTrue(String(describing:error).contains("remove targetUUID"))
        }
    }
    func ddlGroup(_ base: CompleteTransaction,sql: String) -> CompleteTransaction {
        let old=base.events.last!
        let event=DecodedEvent(offset:old.offset,eventSize:old.eventSize,control:.query(QueryControl(database:"poc",sql:Data(sql.utf8),errorCode:0,statusVariables:Data())),rowFlags:nil,eventType:2,eventName:"Query",timestamp:old.timestamp,serverID:old.serverID,nextPosition:old.nextPosition,flags:0,sha256:old.sha256,tableID:nil,database:"poc",table:nil,number:nil,detailBase64:nil,detailText:sql,rows:[],rawBase64:old.rawBase64)
        return CompleteTransaction(start:base.start,end:base.end,gtid:base.gtid,anonymous:false,outcome:.statement,events:[base.events[0],event])
    }
    func testConditionalNoOpAdvancesCheckpointWithoutRetiringSchema() throws {
        #if os(Linux)
        let helpers=ApplyTests(name:"fixtures",testClosure:{_ in})
        #else
        let helpers=ApplyTests()
        #endif
        let parent=FileManager.default.temporaryDirectory.appendingPathComponent(UUID().uuidString)
        try FileManager.default.createDirectory(at:parent,withIntermediateDirectories:true)
        defer {try? FileManager.default.removeItem(at:parent)}
        let store=try StateStore(configuration:helpers.config(parent.appendingPathComponent("state").path))
        let groups=try helpers.groups(),table=helpers.tables()[0],db=store.directory.appendingPathComponent("state.sqlite")
        let sql="CREATE TABLE IF NOT EXISTS poc.items(id INT PRIMARY KEY)"
        let group=ddlGroup(groups[0],sql:sql)
        let plan=PreparedDDL(statement:.createIfAbsent(table,.omitted),before:table,after:table,sql:sql)
        try store.begin(group);try store.ddlIntent(plan,event:group.events[1],coordinate:group.start);try store.complete(group,rowCount:0,ddl:plan)
        XCTAssertEqual(try helpers.sqlite(db,"SELECT COUNT(*),SUM(current) FROM schemas"),[["1","1"]])
        XCTAssertEqual(try helpers.sqlite(db,"SELECT before_schema_id=after_schema_id,status FROM ddl_intents"),[["1","DONE"]])
        let mutation=try DMLPlan.make(groups[1],tables:[table])[0]
        try store.begin(groups[1]);try store.intent(0,mutation);try store.rowDone(0);try store.complete(groups[1],rowCount:1)
        XCTAssertEqual(try helpers.sqlite(db,"SELECT COUNT(*) FROM row_intents r JOIN schemas s ON r.schema_id=s.id WHERE s.current=1"),[["1"]])
        let absent=TableName(database:"poc",table:"absent")
        let drop=PreparedDDL(statement:.dropIfPresent(absent),before:nil,after:nil,sql:"DROP TABLE IF EXISTS poc.absent")
        let dropGroup=ddlGroup(groups[2],sql:drop.sql)
        try store.begin(dropGroup);try store.ddlIntent(drop,event:dropGroup.events[1],coordinate:dropGroup.start);try store.complete(dropGroup,rowCount:0,ddl:drop)
        XCTAssertEqual(try helpers.sqlite(db,"SELECT transactions_applied,rows_applied,ddl_applied FROM state"),[["3","1","2"]])
        XCTAssertEqual(try helpers.sqlite(db,"SELECT COUNT(*) FROM schemas"),[["1"]])
    }
    func testDDLJournalVersionsSchemaAndPrunesOnlyUnreferencedCompletedHistory() throws {
        #if os(Linux)
        let helpers=ApplyTests(name:"fixtures",testClosure:{_ in})
        #else
        let helpers=ApplyTests()
        #endif
        let parent=FileManager.default.temporaryDirectory.appendingPathComponent(UUID().uuidString)
        try FileManager.default.createDirectory(at:parent,withIntermediateDirectories:true)
        defer {try? FileManager.default.removeItem(at:parent)}
        let c=try helpers.config(parent.appendingPathComponent("state").path,storage:["historyRetentionSeconds":60])
        var now=Date(timeIntervalSince1970:1_700_000_000),free=Int64.max/4
        let store=try StateStore(configuration:c,now:{now},freeDisk:{_ in free})
        let db=store.directory.appendingPathComponent("state.sqlite"),groups=try helpers.groups(),table=helpers.tables()[0]
        try store.bindTargetIdentity("00000000-0000-0000-0000-000000000001")
        let create=ddlGroup(groups[0],sql:"CREATE TABLE items(id INT PRIMARY KEY) ENGINE=InnoDB")
        let plan=PreparedDDL(statement:.create(table),before:nil,after:table,sql:"CREATE TABLE poc.items (...) ENGINE=MyISAM")
        try store.begin(create)
        XCTAssertThrowsError(try store.complete(create,rowCount:0,ddl:plan))
        try store.ddlIntent(plan,event:create.events[1],coordinate:create.start)
        XCTAssertEqual(try helpers.sqlite(db,"SELECT status FROM ddl_intents"),[["PENDING"]])
        XCTAssertEqual(try helpers.sqlite(db,"SELECT COUNT(*) FROM schemas"),[["0"]])
        try store.complete(create,rowCount:0,ddl:plan)
        let mutation=try DMLPlan.make(groups[1],tables:[table])[0]
        try store.begin(groups[1]);try store.intent(0,mutation);try store.rowDone(0);try store.complete(groups[1],rowCount:1)
        let after=ApplyTable(database:table.database,table:table.table,columns:table.columns.filter{$0.name != "value"},primaryKey:"id")
        let alter=ddlGroup(groups[2],sql:"ALTER TABLE items DROP COLUMN value")
        let change=PreparedDDL(statement:.dropColumn(TableName(database:"poc",table:"items"),"value"),before:table,after:after,sql:"ALTER TABLE `poc`.`items` DROP COLUMN `value`")
        try store.begin(alter);try store.ddlIntent(change,event:alter.events[1],coordinate:alter.start);try store.complete(alter,rowCount:0,ddl:change)
        XCTAssertEqual(try helpers.sqlite(db,"SELECT current FROM schemas ORDER BY id"),[["0"],["1"]])
        XCTAssertEqual(try helpers.sqlite(db,"SELECT transactions_applied,rows_applied,ddl_applied FROM state"),[["3","1","2"]])
        let drop=ddlGroup(groups[3],sql:"DROP TABLE items")
        let removal=PreparedDDL(statement:.drop(TableName(database:"poc",table:"items")),before:after,after:nil,sql:"DROP TABLE `poc`.`items`")
        try store.begin(drop);try store.ddlIntent(removal,event:drop.events[1],coordinate:drop.start)
        now.addTimeInterval(120);free=c.policy.minimumFreeDiskBytes+c.policy.maximumSQLiteBytes*3/2
        try store.ensureCapacity()
        XCTAssertEqual(try helpers.sqlite(db,"SELECT status FROM ddl_intents"),[["PENDING"]])
        XCTAssertEqual(try helpers.sqlite(db,"SELECT current FROM schemas"),[["1"]])
        XCTAssertEqual(try store.durableAppliedGTIDs(),helpers.sid+":1-13")
        XCTAssertEqual(try helpers.sqlite(db,"SELECT COUNT(*) FROM row_intents"),[["0"]])
    }
}
