import XCTest
import Foundation
@testable import ReplicatorApply
@testable import ReplicatorCodec

final class ReverseDDLTests: XCTestCase {
    func testEngineContractIsSelectedWithoutEngineRewriting() throws {
        func parse(_ engine: String, _ profile: ReplicationProfile) throws -> DDLStatement {
            try DDLStatement.parse(QueryControl(database:"poc",sql:Data("CREATE TABLE t(id INT PRIMARY KEY) ENGINE=\(engine)".utf8),errorCode:0,statusVariables:Data()),profile:profile)
        }
        for engine in ["InnoDB","'InnoDB'"] {
            for profile in ReplicationProfile.allCases where profile.transactional {
                guard case .create(_,let selected)=try parse(engine,profile) else { return XCTFail("missing CREATE") }
                XCTAssertEqual(selected,.innoDB)
                XCTAssertThrowsError(try parse("MyISAM",profile))
                XCTAssertThrowsError(try parse("MEMORY",profile))
            }
            XCTAssertThrowsError(try parse(engine,.mysql84To57MyISAM))
            XCTAssertThrowsError(try parse(engine,.mysql57To57MyISAM))
        }
        XCTAssertThrowsError(try parse("MyISAM",.mysql57To84InnoDB))
        XCTAssertThrowsError(try parse("MEMORY",.mysql57To84InnoDB))
        guard case .create(_,let selected)=try parse("'DEFAULT'",.mysql57To84InnoDB) else { return XCTFail("missing CREATE") }
        XCTAssertEqual(selected,.defaultEngine)
    }
    func testObjectRejectionDoesNotDependOnUnsupportedSessionMetadata() throws {
        var policy=DDLPolicy(); policy.triggers="reject"
        for object in ["TRIGGER","EVENT"] {
            let query=QueryControl(database:"poc",sql:Data("CREATE \(object) name".utf8),errorCode:0,statusVariables:Data([255]))
            XCTAssertThrowsError(try policy.skippedQuery(query,profile:.mysql57To84InnoDB)) {
                XCTAssertTrue(String(describing:$0).contains("DDL policy rejects"))
            }
        }
    }
    func testForeignKeyDDLHasAnExplicitDiagnostic() throws {
        let query=QueryControl(database:"poc",sql:Data("CREATE TABLE t(id INT PRIMARY KEY,n INT,FOREIGN KEY(n) REFERENCES parent(id))".utf8),errorCode:0,statusVariables:Data())
        XCTAssertThrowsError(try DDLStatement.parse(query,profile:.mysql84To57MyISAM)) {
            XCTAssertTrue(String(describing:$0).contains("foreign keys are unsupported"))
        }
    }
    func testSupplementaryEnumAndSetLabelsRejectBeforeExecution() throws {
        for type in ["ENUM","SET"] {
            for profile in ReplicationProfile.allCases {
                let query=QueryControl(database:"poc",sql:Data("CREATE TABLE t(id INT PRIMARY KEY,v \(type)('🙂'))".utf8),errorCode:0,statusVariables:Data())
                XCTAssertThrowsError(try DDLStatement.parse(query,profile:profile)) {
                    XCTAssertTrue(String(describing:$0).contains("supplementary-plane labels"))
                }
            }
        }
    }
    func testTemporaryCleanupIsNarrowAndAuditable() throws {
        func query(_ sql: String) -> QueryControl { QueryControl(database:"poc",sql:Data(sql.utf8),errorCode:0,statusVariables:Data()) }
        let cleanup=query("DROP TEMPORARY TABLE IF EXISTS `a`, `poc`.`b` /* generated by server */")
        let skipped=try DDLPolicy().skippedQuery(cleanup,profile:.mysql57To84InnoDB)
        XCTAssertEqual(skipped?.reason,"row replication temporary-table cleanup")
        XCTAssertEqual(skipped?.sql,String(decoding:cleanup.sql,as:UTF8.self))
        XCTAssertEqual(try DDLPolicy().skippedQuery(cleanup,profile:.mysql57To57MyISAM)?.reason,skipped?.reason)
        XCTAssertNil(try DDLPolicy().skippedQuery(cleanup,profile:.mysql84To57MyISAM))
        XCTAssertNil(try DDLPolicy().skippedQuery(query("DROP TABLE IF EXISTS a"),profile:.mysql57To84InnoDB))
        XCTAssertThrowsError(try DDLPolicy().skippedQuery(query("DROP TEMPORARY TABLE a"),profile:.mysql57To84InnoDB))
        XCTAssertThrowsError(try DDLPolicy().skippedQuery(query("DROP TEMPORARY TABLE IF EXISTS a; DROP TABLE b"),profile:.mysql57To84InnoDB))
    }
    func testMySQL84BinaryDefaultMetadata() throws {
        XCTAssertEqual(try TargetColumnMetadata.defaultValue("0x6869",type:"binary(5)",mysql84:true),"hi\0\0\0")
        XCTAssertEqual(try TargetColumnMetadata.defaultValue("0x6869",type:"varbinary(5)",mysql84:true),"hi")
        XCTAssertEqual(try TargetColumnMetadata.defaultValue("0x6869",type:"varchar(20)",mysql84:true),"0x6869")
        XCTAssertEqual(try TargetColumnMetadata.defaultValue("0x68",type:"binary(4)",mysql84:false),"0x68")
        XCTAssertThrowsError(try TargetColumnMetadata.defaultValue("0x1",type:"binary(4)",mysql84:true))
    }
    func testSQLModeMatchesNativeObsoleteMaskWithoutDiscardingUnknownBits() {
        let contract=MySQL84InnoDBContract()
        // Preserve ANSI_QUOTES, NO_BACKSLASH_ESCAPES and strict behavior.
        let live: UInt64=4 | 1048576 | 4194304
        XCTAssertEqual(contract.ddlSQLMode(live | 0x1003ff00),live)
        XCTAssertEqual(contract.ddlSQLMode(1 << 63),1 << 63)
        XCTAssertEqual(MySQL57MyISAMContract().ddlSQLMode(0x1003ff00),0x1003ff00)
    }
    func testNormalizeOnlySupportedTemporalDefaultPresentation() {
        XCTAssertEqual(TargetColumnMetadata.temporalDefault("current_timestamp()",type:"timestamp"),"CURRENT_TIMESTAMP")
        XCTAssertEqual(TargetColumnMetadata.temporalDefault("current_timestamp(6)",type:"datetime(6)"),"CURRENT_TIMESTAMP(6)")
        XCTAssertEqual(TargetColumnMetadata.extra("DEFAULT_GENERATED on update CURRENT_TIMESTAMP(6)",defaultValue:"current_timestamp(6)",type:"datetime(6)"),"on update CURRENT_TIMESTAMP(6)")
        XCTAssertNil(TargetColumnMetadata.extra("DEFAULT_GENERATED",defaultValue:"current_timestamp()",type:"timestamp"))
        XCTAssertEqual(TargetColumnMetadata.extra("DEFAULT_GENERATED",defaultValue:"(1 + 2)",type:"int"),"DEFAULT_GENERATED")
        XCTAssertEqual(TargetColumnMetadata.temporalDefault("current_timestamp()",type:"varchar(30)"),"current_timestamp()")
    }
}
