import XCTest
import Foundation
@testable import ReplicatorApply
@testable import ReplicatorCodec
@testable import ReplicatorCapture

final class TableFilterTests: XCTestCase {
    var helper: ApplyTests {
        #if os(Linux)
        return ApplyTests(name:"fixtures",testClosure:{_ in})
        #else
        return ApplyTests()
        #endif
    }
    func testLikeWildcardsEscapesCaseAndDatabaseScope() throws {
        let f = try TableFilter(["temp.%", "poc.ignore\\_%", "scratch_.%", "literal.a\\%b", "slash.a\\\\b"])
        XCTAssertTrue(f.ignores(database: "temp", table: "anything"))
        XCTAssertTrue(f.ignores(database: "temp")); XCTAssertFalse(f.ignores(database: "poc"))
        XCTAssertFalse(f.ignores(database: "Temp", table: "anything"))
        XCTAssertTrue(f.ignores(database: "poc", table: "ignore_me")); XCTAssertFalse(f.ignores(database: "poc", table: "ignoreXme"))
        XCTAssertTrue(f.ignores(database: "scratch1", table: "x")); XCTAssertFalse(f.ignores(database: "scratch12", table: "x"))
        XCTAssertTrue(f.ignores(database: "literal", table: "a%b")); XCTAssertFalse(f.ignores(database: "literal", table: "axxb"))
        XCTAssertTrue(f.ignores(database: "slash", table: "a\\b"))
        XCTAssertFalse(try TableFilter().ignores(database: "temp", table: "x"))
        for bad in ["", "temp", ".%", "temp.", "temp.x.y", "temp.x\\"] { XCTAssertThrowsError(try TableFilter([bad])) }
    }
    func query(_ sql: String) -> QueryControl { QueryControl(database: "poc", sql: Data(sql.utf8), errorCode: 0, statusVariables: Data()) }
    func testExcludedDDLBypassesSchemaSubsetButIncludesUseObjectIdentity() throws {
        let f = try TableFilter(["temp.%", "poc.ignore\\_%"])
        for sql in ["CREATE SCHEMA temp", "ALTER DATABASE temp CHARACTER SET latin1", "DROP DATABASE IF EXISTS temp", "CREATE TABLE temp.t(d DECIMAL(30,8),j JSON) ENGINE=InnoDB", "ALTER TABLE temp.t MODIFY d DECIMAL(32,9)", "CREATE FULLTEXT INDEX ix ON temp.t(d)", "DROP INDEX ix ON temp.t", "TRUNCATE temp.t", "DROP TABLE temp.a,temp.b /* generated by server */", "RENAME TABLE temp.a TO temp.b", "CREATE TABLE ignore_t LIKE poc.kept", "/* comment */ CREATE TABLE `temp`.`t` (v VARCHAR(10) DEFAULT 'RENAME TO poc.kept')"] {
            XCTAssertTrue(try f.ignores(query(sql)), sql)
        }
        for sql in ["CREATE TABLE poc.kept LIKE temp.t", "CREATE DATABASE poc", "ALTER TABLE poc.kept RENAME COLUMN a TO b", "GRANT SELECT ON temp.* TO somebody"] {
            XCTAssertFalse(try f.ignores(query(sql)), sql)
        }
        for sql in ["RENAME TABLE temp.a TO poc.kept", "ALTER TABLE temp.a RENAME TO poc.kept", "DROP TABLE temp.a,poc.kept", "CREATE TABLE temp.a(id INT); DROP TABLE poc.kept", "/*!80000 CREATE TABLE temp.a(id INT) */"] {
            XCTAssertThrowsError(try f.ignores(query(sql)), sql)
        }
    }
    func testFilteredGroupAdvancesDurableCheckpointWithoutTargetIntentsAndResumes() throws {
        let helper = self.helper, parent = FileManager.default.temporaryDirectory.appendingPathComponent(UUID().uuidString)
        try FileManager.default.createDirectory(at: parent, withIntermediateDirectories: true)
        defer { try? FileManager.default.removeItem(at: parent) }
        let c = try helper.config(parent.appendingPathComponent("state").path), group = try helper.groups()[0]
        do {
            let store = try StateStore(configuration: c)
            try store.bindTargetIdentity("aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee"); try store.running()
            for event in group.events { try store.append(LiveRecord(kind:"event",file:group.start.file,observedPosition:String(event.nextPosition),event:event,rawBase64:nil)) }
            try store.begin(group); try store.complete(group, rowCount: 0, filtered: true); try store.stopped()
            XCTAssertEqual(store.rows, 0); XCTAssertEqual(store.ddlApplied, 0)
            XCTAssertEqual(store.applied, group.end)
        }
        let reopened = try StateStore(configuration: c, initialize: false)
        XCTAssertEqual(reopened.transactions, 1)
        XCTAssertTrue(reopened.gtids.hasSuffix(":1-11"))
        XCTAssertEqual(try helper.sqlite(reopened.directory.appendingPathComponent("state.sqlite"), "SELECT (SELECT COUNT(*) FROM row_intents),(SELECT COUNT(*) FROM ddl_intents),(SELECT COUNT(*) FROM schemas)"), [["0", "0", "0"]])
    }
    func testFilteredDMLDoesNotNeedATargetSchemaAndIncludedRowsStillValidate() throws {
        let helper = self.helper, group = try helper.groups()[0]
        let events = group.events.map { original -> DecodedEvent in
            var event = original
            if event.rowFlags != nil { event.replicationFiltered = true }
            return event
        }
        let ignored = CompleteTransaction(start: group.start, end: group.end, gtid: group.gtid, anonymous: false, outcome: group.outcome, events: events)
        XCTAssertTrue(try DMLPlan.make(ignored, tables: []).isEmpty)
        XCTAssertThrowsError(try DMLPlan.make(group, tables: []))
    }
}
