import Foundation
import ReplicatorCodec
import MySQLNIO

struct TableName: Equatable {
    let database: String
    let table: String
    var identity: String {database + "\0" + table}
    var sql: String {get throws {try quoted(database)+"."+quoted(table)}}
}
enum ColumnPlacement: Equatable {case last, first, after(String)}
enum DDLEngine: Equatable {case omitted,defaultEngine,myISAM}
struct CreateDatabase: Equatable {
    let name:String
    let ifNotExists:Bool
    let characterSet:String?
    let collation:String?
}
struct PreparedDatabaseDDL: Codable {
    let name:String
    let before:DDLEncoding?
    let after:DDLEncoding
    let serverCollation:String?
}
enum DDLStatement: Equatable {
    case createDatabase(CreateDatabase)
    case create(ApplyTable,DDLEngine = .omitted)
    case createIfAbsent(ApplyTable,DDLEngine)
    case createLike(TableName,TableName,ifNotExists:Bool)
    case add(TableName,ApplyColumn,ColumnPlacement)
    case modify(TableName,ApplyColumn,ColumnPlacement?)
    case indexes(TableName,IndexChange)
    case dropColumn(TableName,String)
    case rename(TableName,TableName)
    case drop(TableName)
    case dropIfPresent(TableName)
    case truncate(TableName)
    var name: TableName? {
        switch self {
        case .createDatabase: return nil
        case .create(let t,_),.createIfAbsent(let t,_): return TableName(database:t.database,table:t.table)
        case .modify(let t,_,_),.indexes(let t,_),.add(let t,_,_),.dropColumn(let t,_),.rename(let t,_),.drop(let t),.dropIfPresent(let t),.createLike(let t,_,_),.truncate(let t): return t
        }
    }
    static func parse(_ query: QueryControl) throws -> DDLStatement {
        try require(query.errorCode == 0,"DDL source query reported an error")
        var parser=try DDLParser(query.sql,database:query.database)
        return try parser.parse()
    }
    static func from(_ group: CompleteTransaction) throws -> DDLStatement {
        try require(group.outcome == .statement && group.gtid != nil && !group.anonymous && group.events.count == 2,"DDL requires a standalone named-GTID query group")
        guard case .gtid = group.events[0].control,case .query(let query)=group.events[1].control else {throw ApplyError("invalid DDL event group")}
        return try parse(query)
    }
}
struct PreparedDDL {
    let statement: DDLStatement
    let before: ApplyTable?
    let after: ApplyTable?
    let sql: String
    var database:PreparedDatabaseDDL? = nil
    var preservesSchema: Bool {
        switch statement {
        case .createIfAbsent, .createLike(_,_,true): return before != nil && before == after
        case .dropIfPresent: return before == nil && after == nil
        default: return false
        }
    }
}

/// Classification and schema prediction for a bounded grammar. The original SQL
/// is executed only after complete parsing and historical default resolution.
/// ASCII identifiers, no expressions and NULL-only defaults keep unused session
/// variables irrelevant; charset-only definitions still require query context.
private struct DDLParser {
    struct Token {let text: String; let identifier: Bool}
    var tokens: [Token]=[]
    var index=0
    let database: String?
    init(_ data: Data,database: String?) throws {
        self.database=database
        try require(data.count <= 65536,"DDL statement exceeds 64 KiB")
        guard var sql=String(data:data,encoding:.utf8),sql.unicodeScalars.allSatisfy({$0.isASCII}) else {throw ApplyError("DDL requires ASCII SQL and identifiers")}
        sql=sql.trimmingCharacters(in:.whitespacesAndNewlines)
        // MySQL 8.4 regenerates DROP TABLE with this exact non-executable suffix.
        let suffix="/* generated by server */"
        if sql.hasSuffix(suffix) {sql=String(sql.dropLast(suffix.count)).trimmingCharacters(in:.whitespacesAndNewlines)}
        let bytes=Array(sql.utf8); var i=0
        while i<bytes.count {
            let c=bytes[i]
            if [9,10,13,32].contains(c) {i+=1;continue}
            if c==39 {
                i+=1;let start=i
                while i<bytes.count && bytes[i] != 39 {i+=1}
                try require(i<bytes.count,"unterminated DDL engine literal")
                tokens.append(Token(text:"\'"+String(decoding:bytes[start..<i],as:UTF8.self)+"\'",identifier:false));i+=1
            } else if c==96 {
                i+=1;var name=[UInt8]();var closed=false
                while i<bytes.count {
                    if bytes[i]==96 {
                        if i+1<bytes.count && bytes[i+1]==96 {name.append(96);i+=2;continue}
                        i+=1;closed=true;break
                    }
                    name.append(bytes[i]);i+=1
                }
                try require(closed,"unterminated DDL identifier")
                try require(!name.contains(92) && name.allSatisfy{$0>=32 && $0 != 127},"unsupported escape/control byte in DDL identifier")
                tokens.append(Token(text:String(decoding:name,as:UTF8.self),identifier:true))
            } else if (65...90).contains(c) || (97...122).contains(c) || (48...57).contains(c) || c==95 || c==36 {
                let start=i;i+=1
                while i<bytes.count {
                    let n=bytes[i]
                    if !((65...90).contains(n) || (97...122).contains(n) || (48...57).contains(n) || n==95 || n==36) {break}
                    i+=1
                }
                tokens.append(Token(text:String(decoding:bytes[start..<i],as:UTF8.self),identifier:false))
            } else if [40,41,44,46,59,61].contains(c) {
                tokens.append(Token(text:String(UnicodeScalar(c)),identifier:false));i+=1
            } else {throw ApplyError("unsupported DDL token or comment")}
            try require(tokens.count<=4096,"DDL token limit exceeded")
        }
    }
    func isNext(_ word: String) -> Bool {index<tokens.count && !tokens[index].identifier && tokens[index].text.uppercased()==word}
    mutating func take(_ word: String) -> Bool {if isNext(word) {index+=1;return true};return false}
    mutating func expect(_ word: String) throws {try require(take(word),"unsupported DDL: expected \(word)")}
    mutating func identifier() throws -> String {
        try require(index<tokens.count,"missing DDL identifier")
        let token=tokens[index];index+=1
        try require(token.identifier || token.text.utf8.allSatisfy { (65...90).contains($0) || (97...122).contains($0) || (48...57).contains($0) || $0==95 || $0==36 },"invalid DDL identifier")
        _ = try quoted(token.text);return token.text
    }
    mutating func name() throws -> TableName {
        let first=try identifier()
        if take(".") {return TableName(database:first,table:try identifier())}
        guard let database,!database.isEmpty else {throw ApplyError("unqualified DDL table without default database")}
        _ = try quoted(database);return TableName(database:database,table:first)
    }
    mutating func column() throws -> (ApplyColumn,Bool) {
        let name=try identifier();let type: String
        if take("INT") || take("INTEGER") {type="int"+(take("UNSIGNED") ? " unsigned" : "")}
        else if take("BIGINT") {type="bigint"+(take("UNSIGNED") ? " unsigned" : "")}
        else if take("DATE") {type="date"}
        else if isNext("VARCHAR") || isNext("VARBINARY") || isNext("CHAR") || isNext("BINARY") {
            let base=tokens[index].text.lowercased();index+=1
            try expect("(");let length=try identifier();try expect(")")
            try require(Int(length) != nil,"invalid DDL column width");type=base+"("+length+")"
        } else {throw ApplyError("unsupported DDL column type")}
        var nullable=true,primary=false,collation: String?,charset: String?,seen=Set<String>()
        while index<tokens.count {
            let attribute: String
            if take("NOT") {try expect("NULL");nullable=false;attribute="nullability"}
            else if take("NULL") {nullable=true;attribute="nullability"}
            else if take("PRIMARY") {try expect("KEY");primary=true;attribute="primary"}
            else if take("DEFAULT") {try expect("NULL");attribute="default"}
            else if take("CHARACTER") {
                try expect("SET");charset=try identifier().lowercased();attribute="charset"
            } else if take("COLLATE") {collation=try identifier().lowercased();attribute="collation"}
            else {break}
            try require(seen.insert(attribute).inserted,"duplicate DDL column attribute")
        }
        if primary {nullable=false}
        try require(!seen.contains("default") || nullable,"DEFAULT NULL on nonnullable DDL column")
        var column=ApplyColumn(name:name,type:type,nullable:nullable,collation:collation)
        column.characterSet=charset
        // VARCHAR defaults are resolved against the historical target schema later.
        if !type.hasPrefix("varchar(") && !type.hasPrefix("char(") {try require(charset==nil,"charset on non-text column");try column.validate()}
        return (column,primary)
    }
    mutating func placement() throws -> ColumnPlacement? {
        if take("FIRST") {return .first}
        if take("AFTER") {return .after(try identifier())}
        return nil
    }
    mutating func keyParts() throws -> [ApplyIndexPart] {
        try expect("("); var parts:[ApplyIndexPart]=[]
        repeat {
            let column=try identifier(); var prefix:Int?
            if take("(") {
                let value=try identifier()
                guard let n=Int(value),n>0 else {throw ApplyError("invalid index prefix")}
                prefix=n;try expect(")")
            }
            _ = take("ASC")
            parts.append(ApplyIndexPart(column:column,prefix:prefix))
            try require(parts.count<=16,"index part limit exceeded")
        } while take(",")
        try expect(")");return parts
    }
    mutating func indexDefinition() throws -> ApplyIndex {
        let unique=take("UNIQUE")
        try require(take("INDEX") || take("KEY"),"expected INDEX or KEY")
        let name=try identifier();let using=take("USING")
        if using {try expect("BTREE")}
        let parts=try keyParts()
        if take("USING") {try require(!using,"duplicate index type");try expect("BTREE")}
        return ApplyIndex(name:name,unique:unique,parts:parts)
    }
    mutating func parse() throws -> DDLStatement {
        let result: DDLStatement
        if take("CREATE") {
            if isNext("INDEX") || isNext("UNIQUE") {
                let unique=take("UNIQUE");try expect("INDEX");let key=try identifier()
                let using=take("USING");if using {try expect("BTREE")}
                try expect("ON");let table=try name();let parts=try keyParts()
                if take("USING") {try require(!using,"duplicate index type");try expect("BTREE")}
                result = .indexes(table,.add(ApplyIndex(name:key,unique:unique,parts:parts)))
            } else if take("DATABASE") || take("SCHEMA") {
                let conditional=take("IF")
                if conditional {try expect("NOT");try expect("EXISTS")}
                let name=try identifier()
                var charset:String?,collation:String?,seen=Set<String>()
                while index<tokens.count && !isNext(";") {
                    _ = take("DEFAULT")
                    let option:String
                    if take("CHARACTER") {try expect("SET");_ = take("=");charset=try identifier().lowercased();option="charset"}
                    else if take("CHARSET") {_ = take("=");charset=try identifier().lowercased();option="charset"}
                    else if take("COLLATE") {_ = take("=");collation=try identifier().lowercased();option="collation"}
                    else {throw ApplyError("unsupported CREATE DATABASE option")}
                    try require(seen.insert(option).inserted,"duplicate CREATE DATABASE option")
                }
                result = .createDatabase(CreateDatabase(name:name,ifNotExists:conditional,characterSet:charset,collation:collation))
            } else {
                try expect("TABLE")
                let conditional=take("IF")
                if conditional {try expect("NOT");try expect("EXISTS")}
                let table=try name()
                if take("LIKE") {
                    result = .createLike(table,try name(),ifNotExists:conditional)
                } else {
                    try expect("(")
                    var columns=[ApplyColumn](),key: [String]?
                    repeat {
                        if take("PRIMARY") {
                            try expect("KEY");try expect("(");var names=[String]()
                            repeat { names.append(try identifier()); try require(names.count<=16,"primary-key column limit exceeded") } while take(",")
                            try expect(")")
                            try require(key==nil && Set(names).count == names.count,"multiple or duplicate DDL primary keys");key=names
                        } else {
                            let (column,primary)=try column();columns.append(column)
                            try require(columns.count<=256,"DDL column limit exceeded")
                            if primary {try require(key==nil,"multiple DDL primary keys");key=[column.name]}
                        }
                    } while take(",")
                    try expect(")")
                    var tableCharset:String?,tableCollation:String?,options=Set<String>()
                    var engine=DDLEngine.omitted
                    while index<tokens.count && !isNext(";") {
                        let option:String
                        if take("ENGINE") {
                            _ = take("=");option="engine"
                            if take("MYISAM") || take("'MYISAM'") {engine = .myISAM}
                            else if take("'DEFAULT'") {engine = .defaultEngine}
                            else {throw ApplyError("explicit engine is outside the MyISAM DDL contract (no engine rewriting)")}
                        } else {
                            _ = take("DEFAULT")
                            if take("CHARACTER") {try expect("SET");_ = take("=");tableCharset=try identifier().lowercased();option="charset"}
                            else if take("CHARSET") {_ = take("=");tableCharset=try identifier().lowercased();option="charset"}
                            else if take("COLLATE") {_ = take("=");tableCollation=try identifier().lowercased();option="collation"}
                            else {throw ApplyError("unsupported CREATE TABLE option")}
                        }
                        try require(options.insert(option).inserted,"duplicate CREATE TABLE option")
                    }
                    guard let key else {throw ApplyError("DDL CREATE requires a primary key")}
                    columns=columns.map { c in
                        if !key.contains(c.name) {return c}
                        var keyColumn=ApplyColumn(name:c.name,type:c.type,nullable:false,collation:c.collation);keyColumn.characterSet=c.characterSet;return keyColumn
                    }
                    var schema=ApplyTable(database:table.database,table:table.table,columns:columns,primaryKeyColumns:key)
                    schema.defaultCharacterSet=tableCharset;schema.defaultCollation=tableCollation
                    result = conditional ? .createIfAbsent(schema,engine) : .create(schema,engine)
                }
            }
        } else if take("ALTER") {
            try expect("TABLE");let table=try name()
            if take("ADD") {
                if isNext("UNIQUE") || isNext("INDEX") || isNext("KEY") { result = .indexes(table,.add(try indexDefinition())) }
                else {
                    _ = take("COLUMN");let (column,primary)=try column()
                    try require(column.nullable && !primary,"DDL ADD only supports nullable non-key columns")
                    result = .add(table,column,try placement() ?? .last)
                }
            } else if take("MODIFY") {
                _ = take("COLUMN");let (column,primary)=try column()
                try require(!primary,"MODIFY cannot change primary-key membership")
                result = .modify(table,column,try placement())
            } else if take("DROP") {
                if take("INDEX") || take("KEY") {
                    let old=try identifier()
                    if take(",") { try expect("ADD");result = .indexes(table,.replace(old,try indexDefinition())) }
                    else {result = .indexes(table,.drop(old))}
                } else {_ = take("COLUMN");result = .dropColumn(table,try identifier())}
            } else if take("RENAME") {
                try require(take("INDEX") || take("KEY"),"unsupported ALTER RENAME operation")
                let old=try identifier();try expect("TO");result = .indexes(table,.rename(old,try identifier()))
            } else {throw ApplyError("unsupported ALTER TABLE operation")}
        } else if take("RENAME") {
            try expect("TABLE");let from=try name();try expect("TO");let to=try name()
            try require(from.database==to.database && from != to,"DDL rename requires distinct names in one database")
            result = .rename(from,to)
        } else if take("DROP") {
            if take("INDEX") {let key=try identifier();try expect("ON");result = .indexes(try name(),.drop(key))}
            else {
                try expect("TABLE");let conditional=take("IF")
                if conditional {try expect("EXISTS")}
                let table=try name();result = conditional ? .dropIfPresent(table) : .drop(table)
            }
        }
        else if take("TRUNCATE") {_ = take("TABLE");result = .truncate(try name())}
        else {throw ApplyError("unsupported DDL statement")}
        _ = take(";")
        try require(index==tokens.count,"unsupported trailing DDL clause or additional statement")
        return result
    }
}

struct DDLEncoding: Equatable, Codable {let characterSet:String;let collation:String}

extension TargetSession {
    func tableExists(_ name: TableName) throws -> Bool {
        try scalar("SELECT COUNT(*) AS v FROM information_schema.TABLES WHERE TABLE_SCHEMA=? AND TABLE_NAME=?",[.init(string:name.database),.init(string:name.table)]) != "0"
    }
    func tableEncoding(_ name:TableName) throws -> DDLEncoding {
        guard let row=try query("SELECT c.CHARACTER_SET_NAME,t.TABLE_COLLATION FROM information_schema.TABLES t JOIN information_schema.COLLATIONS c ON c.COLLATION_NAME=t.TABLE_COLLATION WHERE t.TABLE_SCHEMA=? AND t.TABLE_NAME=?",[.init(string:name.database),.init(string:name.table)]).0.first,
              let charset=row.column("CHARACTER_SET_NAME")?.string,let collation=row.column("TABLE_COLLATION")?.string else {throw ApplyError("missing target table defaults")}
        return DDLEncoding(characterSet:charset,collation:collation)
    }
    func databaseEncoding(_ name:String) throws -> DDLEncoding {
        guard let row=try query("SELECT DEFAULT_CHARACTER_SET_NAME,DEFAULT_COLLATION_NAME FROM information_schema.SCHEMATA WHERE SCHEMA_NAME=?",[.init(string:name)]).0.first,
              let charset=row.column("DEFAULT_CHARACTER_SET_NAME")?.string,let collation=row.column("DEFAULT_COLLATION_NAME")?.string else {throw ApplyError("missing target database defaults")}
        return DDLEncoding(characterSet:charset,collation:collation)
    }
    func resolveEncoding(charset:String?,collation:String?,parent:DDLEncoding?,context:QuerySessionContext) throws -> DDLEncoding {
        if charset==nil && collation==nil {
            guard let parent else {throw ApplyError("missing inherited DDL encoding")}
            return parent
        }
        let rows:[MySQLRow]
        if let collation {
            rows=try query("SELECT CHARACTER_SET_NAME,COLLATION_NAME FROM information_schema.COLLATIONS WHERE COLLATION_NAME=?",[.init(string:collation)]).0
        } else if charset=="utf8mb4" {
            rows=try query("SELECT CHARACTER_SET_NAME,COLLATION_NAME FROM information_schema.COLLATIONS WHERE ID=?",[.init(string:String(context.defaultUTF8MB4Collation))]).0
            // 5.7 cannot set default_collation_for_utf8mb4. Preserve the SQL;
            // refuse a semantic mismatch instead of inserting a COLLATE rewrite.
            let actual=try scalar("SELECT DEFAULT_COLLATE_NAME AS v FROM information_schema.CHARACTER_SETS WHERE CHARACTER_SET_NAME='utf8mb4'")
            try require(rows.first?.column("COLLATION_NAME")?.string==actual,"source default utf8mb4 collation is unsupported by target; no collation substitution")
        } else {
            rows=try query("SELECT CHARACTER_SET_NAME,DEFAULT_COLLATE_NAME AS COLLATION_NAME FROM information_schema.CHARACTER_SETS WHERE CHARACTER_SET_NAME=?",[.init(string:charset!)]).0
        }
        guard let row=rows.first,let found=row.column("CHARACTER_SET_NAME")?.string,let name=row.column("COLLATION_NAME")?.string else {throw ApplyError("unsupported target charset/collation; no substitution")}
        try require(charset==nil || charset==found,"DDL charset/collation mismatch")
        return DDLEncoding(characterSet:found,collation:name)
    }
    func resolveColumn(_ column:ApplyColumn,parent:DDLEncoding,context:QuerySessionContext) throws -> ApplyColumn {
        var result=column
        if column.type.hasPrefix("varchar(") || column.type.hasPrefix("char(") {
            let encoding=try resolveEncoding(charset:column.characterSet,collation:column.collation,parent:parent,context:context)
            result.characterSet=encoding.characterSet
            result=ApplyColumn(name:column.name,type:column.type,nullable:column.nullable,collation:encoding.collation,characterSet:encoding.characterSet)
        }
        try result.validate();return result
    }
    func prepareDDL(_ statement: DDLStatement,query source:QueryControl) throws -> PreparedDDL {
        try unlock()
        try invalidateStatements()
        try writerExclusion()
        let context=try QuerySessionContext(query:source)
        // The accepted grammar has only ASCII tokens/identifiers, no text literals,
        // expressions, stored programs or timestamp defaults. Database creation
        // additionally restores the logged server collation when it is inherited.
        // Require a known ASCII-compatible client encoding.
        try require([8,33,45,46,83,192,224,255].contains(context.clientCharset),"unsupported DDL client charset")
        if case .createDatabase(let definition)=statement {
            return try prepareDatabaseDDL(statement,definition:definition,source:source,context:context)
        }
        guard let name=statement.name else {throw ApplyError("missing DDL table name")}
        // Read the local LIKE template even when IF NOT EXISTS keeps the
        // destination. MySQL opens the template before testing the destination.
        var template:ApplyTable?
        func checkedSchema(_ name:TableName) throws -> ApplyTable {
            let current=try readSchema(database:name.database,name:name.table)
            if let cached=discovered[name.identity] {try require(current==cached,"target schema drift before DDL")}
            return current
        }
        if case .createLike(_,let source,_)=statement {template=try checkedSchema(source)}
        let exists=try tableExists(name)
        let before:ApplyTable?
        switch statement {
        case .create,.createLike(_,_,false):
            try require(!exists,"DDL CREATE target already exists");before=nil
        case .createIfAbsent,.createLike(_,_,true),.dropIfPresent:
            if exists {before=try checkedSchema(name)}
            else {
                try require(discovered[name.identity]==nil,"target schema disappeared before DDL")
                before=nil
            }
        default: before=try checkedSchema(name)
        }
        var after:ApplyTable?
        switch statement {
        case .createDatabase: throw ApplyError("database DDL reached table prediction")
        case .create(let table,let engine),.createIfAbsent(let table,let engine):
            if let before {after=before;break}
            if engine != .myISAM {
                try require(try scalar("SELECT @@SESSION.default_storage_engine AS v")=="MyISAM","DDL requires target default_storage_engine=MyISAM")
            }
            if engine == .defaultEngine {
                try require(try scalar("SELECT @@SESSION.default_tmp_storage_engine AS v")=="MyISAM","ENGINE='DEFAULT' requires qualified target temporary-engine default")
            }
            let parent=try databaseEncoding(name.database)
            let encoding=try resolveEncoding(charset:table.defaultCharacterSet,collation:table.defaultCollation,parent:parent,context:context)
            after=ApplyTable(database:table.database,table:table.table,columns:try table.columns.map {try resolveColumn($0,parent:encoding,context:context)},primaryKeyColumns:table.primaryKeyColumns,defaultCharacterSet:encoding.characterSet,defaultCollation:encoding.collation)
        case .createLike:
            if let before {after=before}
            else {
                let template=template!
                after=ApplyTable(database:name.database,table:name.table,columns:template.columns,primaryKeyColumns:template.primaryKeyColumns,defaultCharacterSet:template.defaultCharacterSet,defaultCollation:template.defaultCollation,secondaryIndexes:template.secondaryIndexes)
            }
        case .add(_,let column,let placement):
            let encoding=DDLEncoding(characterSet:before!.defaultCharacterSet!,collation:before!.defaultCollation!)
            let column=try resolveColumn(column,parent:encoding,context:context)
            var columns=before!.columns
            try require(!columns.contains(where:{$0.name==column.name}),"DDL ADD column already exists")
            switch placement {
            case .last: columns.append(column)
            case .first: columns.insert(column,at:0)
            case .after(let key):
                guard let index=columns.firstIndex(where:{$0.name==key}) else {throw ApplyError("DDL AFTER column absent")}
                columns.insert(column,at:index+1)
            }
            after=before!.replacing(columns:columns)
        case .modify(_,let column,let placement):
            let encoding=DDLEncoding(characterSet:before!.defaultCharacterSet!,collation:before!.defaultCollation!)
            let resolved=try resolveColumn(column,parent:encoding,context:context)
            after=try before!.modifying(resolved,placement:placement)
        case .indexes(_,let change):
            after=try change.applying(to:before!)
        case .dropColumn(_,let column):
            try require(!before!.primaryKeyColumns.contains(column) && before!.columns.contains(where:{$0.name==column}),"DDL DROP requires an existing non-key column")
            try require(!before!.secondaryIndexes.contains{$0.parts.contains{$0.column == column}},"DROP of an indexed column is outside this slice")
            after=before!.replacing(columns:before!.columns.filter{$0.name != column})
        case .rename(_,let destination):
            try require(!(try tableExists(destination)),"DDL RENAME destination exists")
            after=ApplyTable(database:destination.database,table:destination.table,columns:before!.columns,primaryKeyColumns:before!.primaryKeyColumns,defaultCharacterSet:before!.defaultCharacterSet,defaultCollation:before!.defaultCollation,secondaryIndexes:before!.secondaryIndexes)
        case .drop,.dropIfPresent: after=nil
        case .truncate: after=before
        }
        try after?.validate()
        try require(discovered.count - (discovered[name.identity] == nil ? 0 : 1) + (after == nil ? 0 : 1) <= maximumCachedTables,"discovered schema limit reached")
        // No SQL rewriting: execute precisely the single parsed source statement.
        let sql=String(decoding:source.sql,as:UTF8.self)
        _ = try self.query("SET SESSION sql_mode=\(context.sqlMode)")
        if let db=source.database,!db.isEmpty {_ = try self.query("USE \(quoted(db))",textProtocol:true)}
        return PreparedDDL(statement:statement,before:before,after:after,sql:sql)
    }
    func prepareDatabaseDDL(_ statement:DDLStatement,definition:CreateDatabase,source:QueryControl,context:QuerySessionContext) throws -> PreparedDDL {
        let exists=try scalar("SELECT COUNT(*) AS v FROM information_schema.SCHEMATA WHERE SCHEMA_NAME=?",[.init(string:definition.name)]) != "0"
        try require(!exists || definition.ifNotExists,"DDL CREATE DATABASE target already exists")
        let before=exists ? try databaseEncoding(definition.name) : nil
        let after:DDLEncoding
        var serverCollation:String?
        if let before {after=before}
        else if definition.characterSet==nil && definition.collation==nil {
            guard let row=try query("SELECT CHARACTER_SET_NAME,COLLATION_NAME FROM information_schema.COLLATIONS WHERE ID=?",[.init(string:String(context.serverCollation))]).0.first,
                  let charset=row.column("CHARACTER_SET_NAME")?.string,let collation=row.column("COLLATION_NAME")?.string else {
                throw ApplyError("unsupported source server collation; no substitution")
            }
            after=DDLEncoding(characterSet:charset,collation:collation);serverCollation=collation
        } else {
            after=try resolveEncoding(charset:definition.characterSet,collation:definition.collation,parent:nil,context:context)
        }
        _ = try query("SET SESSION sql_mode=\(context.sqlMode)")
        // MySQL write_db_cmd_to_binlog sets Query.db to the created database
        // with suppress_use=true. It is not an instruction to USE a missing DB.
        return PreparedDDL(statement:statement,before:nil,after:nil,sql:String(decoding:source.sql,as:UTF8.self),database:PreparedDatabaseDDL(name:definition.name,before:before,after:after,serverCollation:serverCollation))
    }
    func applyDDL(_ plan: PreparedDDL) throws {
        try unlock()
        try invalidateStatements()
        try writerExclusion()
        if let database=plan.database {
            guard let previous=try scalar("SELECT @@SESSION.collation_server AS v") else {throw ApplyError("missing target server collation")}
            if let collation=database.serverCollation {_ = try query("SET SESSION collation_server=?",[.init(string:collation)])}
            _ = try query(plan.sql,textProtocol:true,timeoutSeconds:config.ddlDeadline)
            if database.serverCollation != nil {_ = try query("SET SESSION collation_server=?",[.init(string:previous)])}
            try resetDMLSession()
            try require(try databaseEncoding(database.name)==database.after,"DDL target database defaults mismatch")
            try invalidateStatements()
            return
        }
        guard let name=plan.statement.name else {throw ApplyError("missing prepared database DDL")}
        _ = try query(plan.sql,textProtocol:true,timeoutSeconds:config.ddlDeadline)
        try resetDMLSession()
        if let after=plan.after {try require(try readSchema(database:after.database,name:after.table)==after,"DDL target after-schema mismatch")}
        if case .createLike=plan.statement,plan.before==nil {try require(try scalar("SELECT COUNT(*) AS v FROM \(name.sql)")=="0","CREATE LIKE unexpectedly copied rows")}
        if case .truncate=plan.statement {try require(try scalar("SELECT COUNT(*) AS v FROM \(name.sql)")=="0","TRUNCATE did not empty the table")}
        if plan.after?.identity != name.identity {try require(!(try tableExists(name)),"DDL source table remains after rename/drop")}
        discovered.removeValue(forKey:name.identity)
        if let after=plan.after {discovered[after.identity]=after}
        try invalidateStatements()
    }
}
