import Foundation
import ReplicatorCodec

struct TableName: Equatable {
    let database: String
    let table: String
    var identity: String {database + "\0" + table}
    var sql: String {get throws {try quoted(database)+"."+quoted(table)}}
}
enum ColumnPlacement: Equatable {case last, first, after(String)}
enum DDLStatement: Equatable {
    case create(ApplyTable)
    case add(TableName,ApplyColumn,ColumnPlacement)
    case dropColumn(TableName,String)
    case rename(TableName,TableName)
    case drop(TableName)
    var name: TableName {
        switch self {
        case .create(let t): return TableName(database:t.database,table:t.table)
        case .add(let t,_,_),.dropColumn(let t,_),.rename(let t,_),.drop(let t): return t
        }
    }
    static func parse(_ query: QueryControl) throws -> DDLStatement {
        try require(query.errorCode == 0,"DDL source query reported an error")
        var parser=try DDLParser(query.sql,database:query.database)
        return try parser.parse()
    }
    static func from(_ group: CompleteTransaction) throws -> DDLStatement {
        try require(group.outcome == .statement && group.gtid != nil && !group.anonymous && group.events.count == 2,"DDL requires a standalone named-GTID query group")
        guard case .gtid = group.events[0].control,case .query(let query)=group.events[1].control else {throw ApplyError("invalid DDL event group")}
        return try parse(query)
    }
}
struct PreparedDDL {
    let statement: DDLStatement
    let before: ApplyTable?
    let after: ApplyTable?
    let sql: String
}

/// A deliberately small grammar, not a SQL text rewriter. Only recognized tokens
/// produce target SQL. Literals, expressions, executable comments and extra SQL
/// fail closed. The accepted syntax is independent of source SQL-mode/charset
/// status: ASCII/backtick identifiers, explicit types/encoding, NULL-only defaults.
private struct DDLParser {
    struct Token {let text: String; let identifier: Bool}
    var tokens: [Token]=[]
    var index=0
    let database: String?
    init(_ data: Data,database: String?) throws {
        self.database=database
        try require(data.count <= 65536,"DDL statement exceeds 64 KiB")
        guard var sql=String(data:data,encoding:.utf8),sql.unicodeScalars.allSatisfy({$0.isASCII}) else {throw ApplyError("DDL requires ASCII SQL and identifiers")}
        sql=sql.trimmingCharacters(in:.whitespacesAndNewlines)
        // MySQL 8.4 regenerates DROP TABLE with this exact non-executable suffix.
        let suffix="/* generated by server */"
        if sql.hasSuffix(suffix) {sql=String(sql.dropLast(suffix.count)).trimmingCharacters(in:.whitespacesAndNewlines)}
        let bytes=Array(sql.utf8); var i=0
        while i<bytes.count {
            let c=bytes[i]
            if [9,10,13,32].contains(c) {i+=1;continue}
            if c==96 {
                i+=1;var name=[UInt8]();var closed=false
                while i<bytes.count {
                    if bytes[i]==96 {
                        if i+1<bytes.count && bytes[i+1]==96 {name.append(96);i+=2;continue}
                        i+=1;closed=true;break
                    }
                    name.append(bytes[i]);i+=1
                }
                try require(closed,"unterminated DDL identifier")
                tokens.append(Token(text:String(decoding:name,as:UTF8.self),identifier:true))
            } else if (65...90).contains(c) || (97...122).contains(c) || (48...57).contains(c) || c==95 || c==36 {
                let start=i;i+=1
                while i<bytes.count {
                    let n=bytes[i]
                    if !((65...90).contains(n) || (97...122).contains(n) || (48...57).contains(n) || n==95 || n==36) {break}
                    i+=1
                }
                tokens.append(Token(text:String(decoding:bytes[start..<i],as:UTF8.self),identifier:false))
            } else if [40,41,44,46,59,61].contains(c) {
                tokens.append(Token(text:String(UnicodeScalar(c)),identifier:false));i+=1
            } else {throw ApplyError("unsupported DDL token or comment")}
            try require(tokens.count<=4096,"DDL token limit exceeded")
        }
    }
    func isNext(_ word: String) -> Bool {index<tokens.count && !tokens[index].identifier && tokens[index].text.uppercased()==word}
    mutating func take(_ word: String) -> Bool {if isNext(word) {index+=1;return true};return false}
    mutating func expect(_ word: String) throws {try require(take(word),"unsupported DDL: expected \(word)")}
    mutating func identifier() throws -> String {
        try require(index<tokens.count,"missing DDL identifier")
        let token=tokens[index];index+=1
        try require(token.identifier || token.text.utf8.allSatisfy { (65...90).contains($0) || (97...122).contains($0) || (48...57).contains($0) || $0==95 || $0==36 },"invalid DDL identifier")
        _ = try quoted(token.text);return token.text
    }
    mutating func name() throws -> TableName {
        let first=try identifier()
        if take(".") {return TableName(database:first,table:try identifier())}
        guard let database,!database.isEmpty else {throw ApplyError("unqualified DDL table without default database")}
        _ = try quoted(database);return TableName(database:database,table:first)
    }
    mutating func column() throws -> (ApplyColumn,Bool) {
        let name=try identifier();let type: String
        if take("INT") || take("INTEGER") {type="int"+(take("UNSIGNED") ? " unsigned" : "")}
        else if take("BIGINT") {type="bigint"+(take("UNSIGNED") ? " unsigned" : "")}
        else if isNext("VARCHAR") || isNext("VARBINARY") {
            let base=tokens[index].text.lowercased();index+=1
            try expect("(");let length=try identifier();try expect(")")
            try require(Int(length) != nil,"invalid DDL column width");type=base+"("+length+")"
        } else {throw ApplyError("unsupported DDL column type")}
        var nullable=true,primary=false,collation: String?,seen=Set<String>()
        while index<tokens.count {
            let attribute: String
            if take("NOT") {try expect("NULL");nullable=false;attribute="nullability"}
            else if take("NULL") {nullable=true;attribute="nullability"}
            else if take("PRIMARY") {try expect("KEY");primary=true;attribute="primary"}
            else if take("DEFAULT") {try expect("NULL");attribute="default"}
            else if take("CHARACTER") {
                try expect("SET");try expect("UTF8MB4");try expect("COLLATE")
                let source=try identifier().lowercased()
                collation=source == "utf8mb4_0900_ai_ci" ? "utf8mb4_unicode_ci" : source
                attribute="encoding"
            } else {break}
            try require(seen.insert(attribute).inserted,"duplicate DDL column attribute")
        }
        if primary {nullable=false}
        try require(!seen.contains("default") || nullable,"DEFAULT NULL on nonnullable DDL column")
        let column=ApplyColumn(name:name,type:type,nullable:nullable,collation:collation)
        try column.validate()
        return (column,primary)
    }
    mutating func parse() throws -> DDLStatement {
        let result: DDLStatement
        if take("CREATE") {
            try expect("TABLE");let table=try name();try expect("(")
            var columns=[ApplyColumn](),key: String?
            repeat {
                if take("PRIMARY") {
                    try expect("KEY");try expect("(");let name=try identifier();try expect(")")
                    try require(key==nil,"multiple DDL primary keys");key=name
                } else {
                    let (column,primary)=try column();columns.append(column)
                    try require(columns.count<=256,"DDL column limit exceeded")
                    if primary {try require(key==nil,"multiple DDL primary keys");key=column.name}
                }
            } while take(",")
            try expect(")");try expect("ENGINE");_ = take("=");try expect("INNODB")
            guard let key else {throw ApplyError("DDL CREATE requires a primary key")}
            columns=columns.map { c in c.name==key ? ApplyColumn(name:c.name,type:c.type,nullable:false,collation:c.collation) : c }
            let schema=ApplyTable(database:table.database,table:table.table,columns:columns,primaryKey:key)
            try schema.validate();result = .create(schema)
        } else if take("ALTER") {
            try expect("TABLE");let table=try name()
            if take("ADD") {
                _ = take("COLUMN");let (column,primary)=try column()
                try require(column.nullable && !primary,"DDL ADD only supports nullable non-key columns")
                let placement: ColumnPlacement
                if take("FIRST") {placement = .first}
                else if take("AFTER") {placement = .after(try identifier())}
                else {placement = .last}
                result = .add(table,column,placement)
            } else if take("DROP") {_ = take("COLUMN");result = .dropColumn(table,try identifier())}
            else {throw ApplyError("unsupported ALTER TABLE operation")}
        } else if take("RENAME") {
            try expect("TABLE");let from=try name();try expect("TO");let to=try name()
            try require(from.database==to.database && from != to,"DDL rename requires distinct names in one database")
            result = .rename(from,to)
        } else if take("DROP") {try expect("TABLE");result = .drop(try name())}
        else {throw ApplyError("unsupported DDL statement")}
        _ = take(";")
        try require(index==tokens.count,"unsupported trailing DDL clause or additional statement")
        return result
    }
}

extension TargetSession {
    func tableExists(_ name: TableName) throws -> Bool {
        try scalar("SELECT COUNT(*) AS v FROM information_schema.TABLES WHERE TABLE_SCHEMA=? AND TABLE_NAME=?",[.init(string:name.database),.init(string:name.table)]) != "0"
    }
    func prepareDDL(_ statement: DDLStatement) throws -> PreparedDDL {
        try writerExclusion()
        let name=statement.name
        let before: ApplyTable?
        if case .create = statement {
            try require(!(try tableExists(name)),"DDL CREATE target already exists");before=nil
        } else {
            let current=try readSchema(database:name.database,name:name.table)
            if let cached=discovered[name.identity] {try require(current==cached,"target schema drift before DDL")}
            before=current
        }
        let after: ApplyTable?,sql: String
        switch statement {
        case .create(let t):
            after=t
            let definitions=try t.columns.map(columnSQL)+["PRIMARY KEY (\(try quoted(t.primaryKey)))"]
            sql="CREATE TABLE \(try name.sql) (\(definitions.joined(separator:","))) ENGINE=MyISAM"
        case .add(_,let column,let placement):
            var columns=before!.columns
            try require(!columns.contains(where:{$0.name==column.name}),"DDL ADD column already exists")
            let clause: String
            switch placement {
            case .last: columns.append(column);clause=""
            case .first: columns.insert(column,at:0);clause=" FIRST"
            case .after(let key):
                guard let index=columns.firstIndex(where:{$0.name==key}) else {throw ApplyError("DDL AFTER column absent")}
                columns.insert(column,at:index+1);clause=" AFTER \(try quoted(key))"
            }
            after=ApplyTable(database:name.database,table:name.table,columns:columns,primaryKey:before!.primaryKey)
            sql="ALTER TABLE \(try name.sql) ADD COLUMN \(try columnSQL(column))\(clause)"
        case .dropColumn(_,let column):
            try require(column != before!.primaryKey && before!.columns.contains(where:{$0.name==column}),"DDL DROP requires an existing non-key column")
            after=ApplyTable(database:name.database,table:name.table,columns:before!.columns.filter{$0.name != column},primaryKey:before!.primaryKey)
            sql="ALTER TABLE \(try name.sql) DROP COLUMN \(try quoted(column))"
        case .rename(_,let destination):
            try require(!(try tableExists(destination)),"DDL RENAME destination exists")
            after=ApplyTable(database:destination.database,table:destination.table,columns:before!.columns,primaryKey:before!.primaryKey)
            sql="RENAME TABLE \(try name.sql) TO \(try destination.sql)"
        case .drop: after=nil;sql="DROP TABLE \(try name.sql)"
        }
        try after?.validate()
        try require(discovered.count - (discovered[name.identity] == nil ? 0 : 1) + (after == nil ? 0 : 1) <= 64,"discovered schema limit reached")
        return PreparedDDL(statement:statement,before:before,after:after,sql:sql)
    }
    private func columnSQL(_ column: ApplyColumn) throws -> String {
        var text=try quoted(column.name)+" "+column.type
        if let collation=column.collation {text += " CHARACTER SET utf8mb4 COLLATE "+collation}
        return text+(column.nullable ? " NULL" : " NOT NULL")
    }
    func applyDDL(_ plan: PreparedDDL) throws {
        try writerExclusion()
        _ = try query(plan.sql,textProtocol:true)
        if let after=plan.after {
            try require(try readSchema(database:after.database,name:after.table)==after,"DDL target after-schema mismatch")
        }
        if plan.after?.identity != plan.statement.name.identity {
            try require(!(try tableExists(plan.statement.name)),"DDL source table remains after rename/drop")
        }
        discovered.removeValue(forKey:plan.statement.name.identity)
        if let after=plan.after {discovered[after.identity]=after}
    }
}
